sudo: required

language: node_js

node_js: "8"

cache:
  directories:
    - "node_modules"

before_install:
  - echo -e "machine github.com\n  login mike1pol\n  password $GITHUB_TOKEN" >> ~/.netrc

script:
  - npm run build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run publish;
    fi
