sudo: required

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist
  keep-history: true
  skip-cleanup: false
  verbose: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
