sudo: required

language: node_js

node_js: "8"

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  - ls -al dist

deploy:
  provider: pages
  local-dir: dist/
  keep-history: true
  fqdn: pu.piterjs.org
  skip-cleanup: false
  verbose: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
